# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: Shoov.io
description:
tagline:
url: localhost:4000

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: src
destination: serve

# Same as the title etc for your site but can instead be
# called by using 'site.author.name' and so on
author:
  name: amitaibu
  email: amitai@gizra.com
  bio:
  twitter: amitaibu

# general setting for Jekyll
googleAnalytics: UA-xxxxxxx-xx

# _config.build.yml overwrites these options when you run `gulp build`
# Enables future posts (posts with dates in the future) and drafts
future: true
show_drafts: true
# Disables the more accurate related posts for faster generating of the site
lsi: false
# Only make the last 10 posts so generating isn't slow
limit_posts: 10

# Permalink structure and pagination options
relative_permalinks: true
permalink: pretty
paginate: 10
paginate_path: 'page:num'
excerpt_separator: '<!--more-->'

# Markdown library
markdown: redcarpet
# Markdown library options
redcarpet:
  extensions: ['no_intra_emphasis', 'tables', 'fenced_code_blocks', 'autolink', 'smart',
              'strikethrough', 'superscript', 'underline', 'highlight', 'footnotes']
highlighter: true

# url for the form "action" on submit(#shoov-trial-form).
shoov_trial_form_action: //formspree.io/yaron@gizra.com

# Redirect url after form submittion(#shoov-trial-form).
shoov_trial_form_redirect: http://localhost:3000/?sent=true

# Add a block on page header element that displays the current breakpoint type.
debug_responsive: false
