# Run during the 'gulp build' command
# Overrides these options in _config.yml

# Overrides the default URL, needed for your atom feed and sitemap
url: shoov.io

# general setting for Jekyll
googleAnalytics: UA-6558346-10

# Hides your drafts and future posts
future: false
show_drafts: false
# Gives you more accurate related posts
lsi: true
# Removes the upper limit for posts generated
limit_posts: 0

source: 'src'
destination: 'serve'

# url for the form "action" on submit(#shoov-trial-form).
trial_form_action: //formspree.io/info+shoov@gizra.com

# Redirect url after form submittion(#shoov-trial-form).
trial_form_redirect: http://www.shoov.io/?sent=true
